baseURL = 'https://lderequesens.netlify.app/'
languageCode = 'en-us'
title = 'Pudú Programming'
# Plese change
theme = 'm10c'

[menu]
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[params]
  author = "Leonardo de Requeséns"
  description = "I have been a computer guy all my life. I am passionate about technology and the automation of small tasks. I like video games and board games, piano, hats, cats and more."
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "My Github"
    url = "https://github.com/lderequesensS"
